### ISSUE TITLE
How to place an image in the header (right side of page) aligned with the bottom line?

### ISSUE THREAD

**Issue by krishnakumarg1984** [elauksap/focus-beamertheme#10]
I need to place an image in the header (right side of page) aligned with the bottom line. How can this be achieved in beamertheme-focus?

**Comment by pcafrica** [comment]
Hi @krishnakumarg1984,

unfortunately, currently it is not possible to do what you ask in Focus.
However, I suggest you to manually modify the `beamerouterthemefocus.sty` file: just add the content you need right within the `\defbeamertemplate*{frametitle}{focus}{...}` definition (line 42), using for example a `\includegraphics[...]{..}` command or a `tikzpicture` environment.

Thanks for using Focus!

Best,
Pasquale
