### ISSUE TITLE
Table and Figure numbering of captions

### ISSUE THREAD

**Issue by MiladGhorbaniG** [elauksap/focus-beamertheme#12]
Hi @SFr682k, I used the great template. I faced an issue that when using captions for images and tables, it prints `TABLE: ....` or `FIGURE: ...`. I expected it to be like `TABLE #: ....` . How to fix this setup?

**Comment by pcafrica** [comment]
Hi @MiladGhorbaniG,

thanks for using my theme Focus!

This is not really a Focus issue, rather the default Beamer behaviour.
In order to have numbered captions just add:

```
\setbeamertemplate{caption}[numbered]
```

to your preamble.
