### ISSUE TITLE
Two issues with `\titlepage`

### ISSUE THREAD

**Issue by ghost** [elauksap/focus-beamertheme#13]
Thanks for developing this theme, it is really beautiful.
I have found a couple of issues when typesetting the title page.
First, consider this mwe:
```
\documentclass[aspectratio=169]{beamer}
\usepackage[T1]{fontenc} \usepackage[utf8]{inputenc}
\usetheme{focus}
\title{Presentation title}
\author{Author}
\begin{document}
\begin{frame}
  \titlepage
\end{frame}
\end{document}
```
the 16:9 aspect ratio causes the author to be partially blocked by the top half of the background.
Consider this other mwe:
```
\documentclass[aspectratio=169]{beamer}
\usepackage[T1]{fontenc} \usepackage[utf8]{inputenc}
\usetheme{focus}
\title{Presentation title}
\author{Author}
\begin{document}
  \frame{\titlepage}
\end{document}
```
The title page is not typeset correctly: the top, darker half of the background expands to the whole slide and blocks the author and date information. This happens whether the `aspectratio` option is specified or not. 
These mwes were compiled with Windows 10 1909 64-bit using TeXLive  2020 updated on the 24th of october.

**Comment by elauksap** [comment]
Hi @bob-marcus,

**Comment by pcafrica** [comment]
Hi @bob-marcus,

thanks for using my theme Focus!

I recommend you using
```tex
\begin{frame}
    \maketitle
\end{frame}
```
rather than `\titlepage` or `\frame{\titlepage}`.

This should fix the issue!

Don't hesitate to write again in case of troubles.

**Comment by ghost** [comment]
@elauksap Thanks, it works!

**Comment by pcafrica** [comment]
For your interest: I've just pushed an updated version that makes
```tex
\frame{\titlepage}
```
working.

The update should be available on the major LaTeX distributions in the next few days.

**Comment by ghost** [comment]
Great, thank you again.
