### ISSUE TITLE
Text in footlist

### ISSUE THREAD

**Issue by fxha** [elauksap/focus-beamertheme#15]
Thanks for creating such a beautiful theme. Is it possible to add a footlist text or could you please create an option for the full-width mode? Thanks!

**Comment by pcafrica** [comment]
Hi @fxha,

thanks for using Focus!

What exactly do you mean by _footlist text_? Do you have any screenshot or LaTeX code that generates such a content using other themes?

Best.

**Comment by fxha** [comment]
That you can print a custom text on the bottom left of all slides like:

![](https://www.powerpointninja.com/images/2008/09/footer1.gif)

So you can insert the presentation title or copyright etc. I think an absolute `tikzpicture` should do the job but you need to manipulate the themes [footlist](https://github.com/elauksap/focus-beamertheme/blob/fb7d2b030b7c23485a76a7c72c50d29c9d12da95/beamerouterthemefocus.sty#L123).

**Comment by pcafrica** [comment]
Done, I've just updated the source code!

Please download the latest release v2.8, where I have defined the new command:
```latex
\footlineinfo{Custom footline text}
```

The new release should appear in most LaTeX distributions in the next days.

Thanks for the suggestion, it was highly appreciated!

Best.

**Comment by fxha** [comment]
Thanks again for your quick response and work. Unfortunately, I get an error when `footlineinfo` isn't defined: `Undefined control sequence. \beamer@@tmpl@footline [...]`, and otherwise the change works perfectly fine.

**Comment by pcafrica** [comment]
That has been fixed, too! Thank you again.
