### ISSUE TITLE
No slide if \section*{} 

### ISSUE THREAD

**Issue by thethinker990** [elauksap/focus-beamertheme#16]
Hi, I wanted to create some sections with the `\section*{}` command for better navigation, so they will be added to the sidebar but not to the TOC. Unfortunately it creates a slide for it, which I don't want either. Is there any switch to suppress this behaviour?

BTW: Thank you for your great template, I really appreciate your work.

**Comment by pcafrica** [comment]
Hi @thethinker990,

thanks for using Focus!

Unfortunately, I'm not able to reproduce the issue.

The following minimal working example works as expected, _i.e._ the section page is not created but the section is shown in the PDF content:
```tex
\documentclass{beamer}
\usetheme{focus}

\title{Focus}
\subtitle{Subtitle}
\author{Author 1, Author 2}
\titlegraphic{}
\institute{Institute Name \\ Institute Address}
\date{dd mm yyyy}

\begin{document}
    \begin{frame}
        \maketitle
    \end{frame}
    
    \section*{Section 1}
    \begin{frame}{Frame}
        This is a simple frame.
    \end{frame}
\end{document}
```

Could you please check if it works on your LaTeX system and, in case it does, provide a MWE that shows the issue?

Thanks.

**Comment by thethinker990** [comment]
This is super weird, when I create a new test.tex I can not reproduce a MWE. I deleted all the files which were created by tex.

I downloaded your source again and overwrite all files, now it works fine..

Sorry for this issue.

**Comment by pcafrica** [comment]
I'm glad you solved.
Feel free to re-open the issue in case the problem shows up again.

Enjoy Focus!

Best.

**Comment by thethinker990** [comment]
Okay, thank you. But another question comes up.

Can I suppress the creation of the slide but have to section-feature enabled (I need a TOC).

**Comment by pcafrica** [comment]
You can try as suggested [here](https://stackoverflow.com/questions/4002329/how-to-make-chapter-section-and-subsection-appear-in-the-table-of-contents).

**Comment by thethinker990** [comment]
Thank you, it didn't worked. I will just delete the pages manually with Acrobat later. I can't figure it out. 

I tried all possible combinations of \protect\numberline{\theSection}

```tex
\documentclass{beamer}
\usetheme{focus}

\title{Focus}
\subtitle{Subtitle}
\author{Author 1}
\titlegraphic{}
\institute{Institute Name}
\date{dd mm yyyy}

\renewcommand{\thesection}{\arabic{section}}

\newcommand\sectionC[1]{%
	\section*{#1}%
%    \addcontentsline{toc}{section}{\protect\numberline{\thesection}~~~line added to TOC: section one}
    \addcontentsline{toc}{section}{\protect\thesection~line added to TOC: section}
	\markboth{#1}{#1}
}

\newcommand\subsectionC[1]{%
	\subsection*{#1}%
%    \addcontentsline{toc}{subsection}{\protect\numberline{\thesubsection}~~~line added to TOC: subsection one}
    \addcontentsline{toc}{subsection}{\protect~line added to TOC: subsection}
	\markboth{#1}{#1}
}

\begin{document}
    \begin{frame}
        \maketitle
    \end{frame}
    
    \sectionC{Section 1}
    \subsectionC{SubSection 1.1}
    
    \sectionC{Section 2}
    \subsectionC{SubSection 2.1}
    \subsectionC{SubSection 2.2}
    
    \begin{frame}{Frame}
        \tableofcontents
    \end{frame}
\end{document}
```
