### ISSUE TITLE
need to disable numbering in table of contents

### ISSUE THREAD

**Issue by ghost** [elauksap/focus-beamertheme#17]
the following produces progressbar at the bottom of the slide
```
...
\usetheme[numbering=none]{focus}
...
\begin{document}
...

\begin{frame}{Overview}
  \tableofcontents
\end{frame}

...
\end{document}
```

**Comment by pcafrica** [comment]
Hi @leobeaver,

thanks for using Focus and for reporting the issue!

I've just updated the source code, please download the latest release v2.9.0 where the issue should be fixed.

The new release should appear in most LaTeX distributions in the next days.

Best.
