### ISSUE TITLE
add slide counter to empty theme

### ISSUE THREAD

**Issue by cherti** [elauksap/focus-beamertheme#19]
Currently, it seems the only option to get slide numbers are with having a bar at the bottom, such as [the recently merged PR](https://github.com/elauksap/focus-beamertheme/pull/18). While having that bar is useful to show which section the presentation is in, there are presentations that do not rely on sections for internal structure, and the empty theme is much more suited to those to remove visual clutter and consequentially playing to the theme's name.

However, having slide numbers would still be useful in that case to have the audience ask specific questions to specific slides. Hence, I think it would be useful to add an option to add slide numbers, for example to the bottom right corner, to the empty theme, retaining the usefulness of the clutterfree experience of the empty theme while still unobtrusively providing slide numbers.

I have discussed this briefly with @imntl, who mentioned he'd be up for implement this.

**Comment by pcafrica** [comment]
Dear @cherti,

thanks for using Focus and for reporting your suggestion!

I have implemented a new `[numbering=minimal]` footline style: https://github.com/elauksap/focus-beamertheme/commit/1016dbdb18b476c4b98869a43a4c099ca3919e16

As with other styles, the total frame number can be suppressed with `[totalframenumbering=no]`.

Hope this is of help.

Best.
