### ISSUE TITLE
Numbered bibligraphy

### ISSUE THREAD

**Issue by colombojrj** [elauksap/focus-beamertheme#20]
Hello,

I would like that my bibliography items show numbers instead of a paper icon. Is it possible to do it?

Thanks.

**Comment by pcafrica** [comment]
Dear @colombojrj,

thanks for using Focus!

This question is not Focus-specific but rather related to Beamer itself.

You can get the desired result by adding the following line to your preamble:
```latex
\setbeamertemplate{bibliography item}{\insertbiblabel}
```

Hope this answer solves the issue!
Otherwise, feel free to re-open it.

Best.

**Comment by colombojrj** [comment]
Wow, that pretty much solved my issue. You and your template are just awesome! Thank you very much!!!
