### ISSUE TITLE
problem with the footline & tikzpicture

### ISSUE THREAD

**Issue by inktvis75** [elauksap/focus-beamertheme#22]
Hi, I really like this beamer theme, but there is a little problem, if I use tikzpicture to position an image at the bottom,
it will break the footline (number and total are separated)

 ```
  \begin{tikzpicture}[remember picture, overlay]
          \node[xshift=-25pt,yshift=25pt, opacity=1, inner sep=0pt, scale=0.45, anchor=south east]
              (box) at (current page.south east) {
              \includegraphics{socialmedia}
          };
      \end{tikzpicture}
```
The problem does not exist with other themes

thnx !
![Uploading Screenshot 2022-02-24 at 16.35.11.png…]()

**Comment by inktvis75** [comment]
solution/work-around: \usetheme[numbering=fullbar]{focus}

**Comment by pcafrica** [comment]
Nice @inktvis75! Thanks for using Focus and for sharing a workaround!
