### ISSUE TITLE
\mathrm{d} is using a different font

### ISSUE THREAD

**Issue by colombojrj** [elauksap/focus-beamertheme#23]
Hi,

First, focus is wonderful. I recently needed to type some equations and I noticed that the derivative symbol (with \mathrm) is using a different font style. How may I overcome this issue?

Thanks.

**Comment by pcafrica** [comment]
Hi @colombojrj,

thanks for using Focus and for the appreciation!
And thanks also for the hint, I never realized the mismatch in the math font.

The issue has been just solved, please have a look at the [new demo](https://github.com/elauksap/focus-beamertheme/blob/master/focus-demo/demo-typeset.jpg) and download our latest release!

Thanks again.
Best,
Pasquale

**Comment by colombojrj** [comment]
Hi,

I tested the but it stopped building. I will post my log here: https://pastebin.com/H99qRgZx

It builds with "\usetheme[nofirafonts]{focus}". What may it be?

**Comment by colombojrj** [comment]
Hi,

If I remove the lines 

    \RequirePackage{firamath-otf}
    \unimathsetup{
        math-style = ISO,
        bold-style = ISO,
        mathrm     = sym
    }

then it builds. I believe it is something related to firamath-otf package.

**Comment by pcafrica** [comment]
Dear @colombojrj,

I suspect you are using the PDFLaTeX compiler, right?
The proper loading of Fira fonts requires the use of XeLaTeX, instead.

Can you please try with that?

Best.

**Comment by colombojrj** [comment]
Hi,
I tried with xelatex, also unsuccessfully...

Em qua., 9 de mar. de 2022 às 21:12, Pasquale Claudio Africa <
***@***.***> escreveu:

**Comment by pcafrica** [comment]
Can you please do a clean build and attach the log file?
Thanks!
