### ISSUE TITLE
Having a background image in section frames

### ISSUE THREAD

**Issue by Akronix** [elauksap/focus-beamertheme#3]
Hi!

I have no idea how hard this would be to implement, but I'd love to be able (optionally) to have a background image in the bottom half space for every section frame.

Therefore, the command would look like this:
`\section{introduction}[image=\includegraphics[0.5\paperheight]{intro.jpg}]`

It could be also a `color` option, to set the background color. But I'm especially interested in the image option one.

**Comment by pcafrica** [comment]
Hi Akronix,
first of all thanks for your interest in using Focus!

Unfortunately I don't see any user-friendly way to place a generic image on the section frame that can be implemented in a new release: the user would still have to manually specify its position and size, which is as complex as manually designing a custom section page:

```
\begingroup
    \let\oldsectionpage\sectionpage
    \renewcommand{\sectionpage}{%
        \oldsectionpage%
        \begin{tikzpicture}[overlay, remember picture]
            \node[anchor=north west] at ([shift = {(0, -0.45\paperheight)}] current page.north west) {My custom text or picture};
        \end{tikzpicture}
    }
    \section{Section Title}
\endgroup
```

Place your custom picture or text inside the curly braces of the TikZ `\node` command and adjust the position and size according to your needs.


In any case you can also change the background color locally:
```
\begingroup
    \definecolor{main}{RGB}{0, 0, 0} % Main color of current section page.
    \section{Section Title}
\endgroup
```

I hope this answers to your question.

Thanks again for using Focus!

Best,
Pasquale

**Comment by Akronix** [comment]
Thank you for your rapid respond  @elauksap.
I've been playing with this and I ended up with something working. I actually "rewrite" the whole \section command:

```
\begingroup
    \let\oldsectionpage\sectionpage
    \renewcommand{\sectionpage}{%
        {%
        %~ \oldsectionpage%
        \usebeamercolor{frametitle}\colorlet{focus@@temp}{bg}%
        \begin{tikzpicture}[overlay, remember picture]
            \fill[color=focus@@temp] (current page.north west) rectangle ([shift = {(0, -0.45\paperheight)}] current page.north east);
        \end{tikzpicture}%


        \vspace{-2\baselineskip}
	    \begin{minipage}[b][0.45\paperheight]{\textwidth}
	        \usebeamerfont{sectiontitle}
	        \usebeamercolor[fg]{frametitle}
	        \insertsection
	    \end{minipage}


        \begin{minipage}[t][0.55\paperheight]{\textwidth}
	    \begin{tikzpicture}[overlay, remember picture]
            \node[anchor=north west] at ([shift = {(-0.1, -0.43\paperheight)}] current page.north west) {
            \includegraphics[height=0.55\paperheight, width=\paperwidth]{Images/my-image.jpg}};
        \end{tikzpicture}
	    \end{minipage}
		}%

    }
    \section{section Title}
\endgroup
```

Probably it is still very ugly since I was mostly patching it until I got it working. But couldn't be a good idea to have an optional argument for \section that, in case it is present, it adds the \includegraphics command with `[height=0.55\paperheight, width=\paperwidth]` or maybe some smart logic to crop the image so it fits there, in the middle bottom of the slide, keeping the aspect ratio?

**Comment by pcafrica** [comment]
Yes, it would be a good idea. But what if the user tries to insert an image with the wrong aspect ratio? Should the template show it centered, filled, spanned, or...? I don't think there's a good answer to this question for all possible images.

It would also be nice to let the user choose a fit method, but in the end it's not much more friendly than manually redefining the section page as described in my previous message.

Anyway I'm open to suggestions, please report me your modification proposals if any!

Thanks again.
