### ISSUE TITLE
Errors with biblatex

### ISSUE THREAD

**Issue by vleugelcomplement** [elauksap/focus-beamertheme#4]
Hello,
Thank you for a modern and nice-looking theme!

I have been trying to add a bibliography using  `biblatex`, but encountered several problems with your
theme. The following  MWE fails with
```
! Extra }, or forgotten \endgroup.
\endframe ->\egroup
                    \begingroup \def \@currenvir {frame}
l.16 \end{frame}
```
but compiles with any standard theme.
An error persists on both pdftex and luatex. 

MWE:
```tex
\documentclass{beamer}

\usetheme{focus}
\usepackage[sorting=none]{biblatex}
\addbibresource{xampl.bib}

\begin{document}

\begin{frame}
  \nocite{*}
\end{frame}

\begin{frame}[t,allowframebreaks]
  \frametitle{References}
  \printbibliography
 \end{frame}

\end{document}

```

**Comment by pcafrica** [comment]
Hi taxus.

Thank you for reporting.
I've just released an update (v2.2.1) that fixes the error.

Please re-try with the new version.

Thanks again!

**Comment by vleugelcomplement** [comment]
Hello, @elauksap! 
I can confirm that everything works now. 
Thank you a lot!

**Comment by manuelkuehner-tri** [comment]
@elauksap Can you tell me what the problem was? I have a similar problem with my own theme.

**Comment by pcafrica** [comment]
Hi @manuelkuehner-tri.

Here you find the diff of the commit that solved the issue a while back: https://github.com/elauksap/focus-beamertheme/compare/v2.2...v2.2.1

See in particular line 104 of `beamerinnerthemefocus.sty`.

Best.
