### ISSUE TITLE
References more than one page

### ISSUE THREAD

**Issue by YimianDai** [elauksap/focus-beamertheme#5]
Thanks for your great work.

I am wondering how can I put references in more than one page. If I have 20 papers cited, currently all these references are in one frame and most of them are not visible.

Best wishes

**Comment by pcafrica** [comment]
Hi YimianDai,
thank you for using Focus!

It is already possible to split references over multiple frames using the `[allowframebreaks]` option:
```
\begin{frame}[allowframebreaks]{References}
    \printbibliography
\end{frame}
```

I hope this fixes your issue.

Best,
Pasquale
