### ISSUE TITLE
feature request: Subsection-Page

### ISSUE THREAD

**Issue by paperbenni** [elauksap/focus-beamertheme#6]
I really like the title pages the theme inserts for each section, but it would be really cool if subsections were visible in any way. Some themes like Metropolis solve this by using the space below the text for the subsection. I'm thinking of something like this where "Git" is the subsection. 
![screenshot](https://imgur.com/0uG7nqr.png)

**Comment by pcafrica** [comment]
Hi @paperbenni,

I've just committed a new release with the possibility to generate a subsection page (please refer to the demo for further instructions).

Thanks for using Focus and for providing this suggestion!

Best,
Pasquale

**Comment by paperbenni** [comment]
Awesome. Then it'll arrive in texlive next year, right?

**Comment by pcafrica** [comment]
It has already been submitted to the CTAN and should be available in most LaTeX distributions (including TeXLive) within few days.

**Comment by paperbenni** [comment]
Ok, thanks again for implementing this so quick!
