### ISSUE TITLE
Bibliography overflow

### ISSUE THREAD

**Issue by VincentTam** [elauksap/focus-beamertheme#8]
I've several entries in the bibliography.  The last one gets truncated in the frame.

![Screenshot_2019-07-19_10-49-02](https://user-images.githubusercontent.com/5748535/61522690-24cc9a80-aa13-11e9-8bb9-9441fca4e7bd.png)

**Comment by pcafrica** [comment]
Hi @VincentTam,
thank you for using Focus!

You may use the `[allowframebreaks]` option:
```
\begin{frame}[allowframebreaks]{References}
    \printbibliography
\end{frame}
```
Then LaTeX will take care of distributing the references across multiple pages properly.

I hope this fixes your issue.

Best,
Pasquale

**Comment by VincentTam** [comment]
Thank you.  That solves the problem.
