### ISSUE TITLE
Line Heights of \maketitle are off

### ISSUE THREAD

**Issue by swissmanu** [elauksap/focus-beamertheme#9]
hi elauksap, first things first: thank you very much for your elegant `beamer` theme. i like the esthetics a lot.

do you have any idea why my title page is rendered with wrong line heights (subtitle & author) as in the screenshot below?

<img width="623" alt="image" src="https://user-images.githubusercontent.com/170832/70862246-1212af00-1f3a-11ea-8633-1cc32b156c5d.png">

i don't have any other packages in use right now. just a simple tex document:

```
\documentclass{beamer}
\usetheme{focus}
\title{Focus: \\ A Minimalist Beamer Theme}
\subtitle{Subtitle}
\author{Author 1\texorpdfstring{\\}{,} Author 2}
% \titlegraphic{\includegraphics[scale=1.25]{focuslogo.pdf}}
\institute{Institute Name \\ Institute Address}
\date{dd mm yyyy}

\begin{document}
\begin{frame}
	\maketitle
\end{frame}
\end{document}
```

i can work around these limitations for now by not showing an author... but any advise would be much appreciated. thank you! :)

**Comment by pcafrica** [comment]
Hi @swissmanu!

First of all thank you for using and appreciating Focus!

Unfortunately, I'm not able to reproduce the issue. As you can see in the picture below, compiling your code (both on my MiKTeX and TeXLive installations) results in a correctly spaced title frame.

![screenshot](https://user-images.githubusercontent.com/5830450/70865800-f0c5b900-1f61-11ea-8cea-72b86e807e0f.png)

Which version of Focus are you using? What is your LaTeX compiler?

Best,
Pasquale

**Comment by swissmanu** [comment]
hi pasquale

thanks for your time and trying my tex source on your own.

i am using a docker based tex-environment (https://github.com/swissmanu/docker-latex) and indeed, it seems to be a problem there only (verified with another docker image).
i will investigate and let you know in case i find the actual problem; but most probably it will "just work" suddenly ;)

cheers,
manuel
